### ISSUE TITLE
Warning: declare(encoding=...) ignored because Zend multibyte feature is turned off

### ISSUE THREAD

**Issue by cweiske** [netresearch/t3x-nr_perfanalysis#1]
I get the following warning when using nr_perfanalysis:

> Warning: declare(encoding=...) ignored because Zend multibyte feature is turned off by settings in /var/www/site/htdocs/typo3conf/ext/nr_perfanalysis/Classes/HtmlRenderer.php on line 2

And I do not want to enable this setting because of potential issues on our system.

**Comment by CybotTM** [comment]
we could drop it - not for the above reason, but we can

but any how, any script which includes multi-byte chars in comment, quoted strings or even worse in code, could still break your system

please feel free to send a pull request
